on:
  pull_request:
    types:
      - opened
    branches:
      - 'backport/master_**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check opened release
        uses: jpacareu-meli/is-release-open-action@v5