on:
  pull_request:
    types:
      - opened
    branches:
      - 'develop'
jobs:
  build:
    if: contains(github.head_ref, 'backport/mastser_')
    runs-on: ubuntu-latest
    steps:
      - name: Check opened release
        uses: jpacareu-meli/is-release-open-action@v5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
